name: Run TestNG Tests

on:
  push:
    branches:
      - main  # Chạy khi push code lên nhánh main
  pull_request:
    branches:
      - main  # Chạy khi tạo pull request vào nhánh main

jobs:
  test:
    runs-on: ubuntu-latest  # Sử dụng runner Ubuntu

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Java (TestNG và Maven yêu cầu Java)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Đảm bảo phiên bản Java phù hợp với dự án
          distribution: 'temurin'  # Sử dụng Eclipse Temurin distribution

      # Bước 3: Cài đặt Maven
      - name: Setup Maven
        uses: stefanzweifel/setup-maven@v2
        with:
          maven-version: '3.9.6'  # Phiên bản Maven mới nhất (có thể thay đổi)

      # Bước 4: Chạy TestNG tests
      - name: Run TestNG Tests
        run: mvn clean test -DsuiteXmlFile=src/test/suites/register.xml

      # (Tùy chọn) Bước 5: Tải lên kết quả test (nếu cần)
      - name: Upload Test Results
        if: always()  # Chạy bước này ngay cả khi test thất bại
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/  # Thư mục chứa kết quả TestNG