name: Build and Deploy Allure Report

on:
  push:
    branches:
      - main  # Chạy khi push code lên nhánh main
  pull_request:
    branches:
      - main  # Chạy khi tạo pull request vào nhánh main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Sử dụng runner Ubuntu

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cài đặt Java (TestNG và Maven yêu cầu Java)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven  # Tự động cache dependencies Maven để tăng tốc build

      - name: Verify Maven Installation
        run: mvn --version

      # Bước này sẽ chạy TestNG và tạo các file kết quả Allure trong target/allure-results
      # Class AllureEnvironmentWriter của bạn sẽ tạo environment.properties ở đây
      - name: Build with Maven and Run Tests
        run: mvn clean test

      # Chạy TestNG tests
      #- name: Run TestNG Tests
      #  run: mvn clean test -DsuiteXmlFile=src/test/suites/register.xml -e -X
        # -e: Hiển thị lỗi chi tiết, -X: Hiển thị debug log

      # https://github.com/allure-framework/allure2/releases
      - name: Install Allure Commandline
        run: |
         ALLURE_VERSION=2.34.1
         curl -L https://github.com/allure-framework/allure2/releases/download/$ALLURE_VERSION/allure-$ALLURE_VERSION.zip -o allure.zip
         sudo unzip allure.zip -d /opt/
         echo "/opt/allure-$ALLURE_VERSION/bin" >> $GITHUB_PATH

      - name: Verify Allure Results
        run: ls -la target/allure-results/ || echo "Allure results not found"

      # Sử dụng Allure CLI để tạo report tĩnh từ các kết quả
      # Allure CLI sẽ tìm environment.properties trong target/allure-results
      - name: Generate Allure Report
        run: allure generate target/allure-results --output target/allure-report --clean

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report # Thư mục chứa report tĩnh đã được tạo

  deploy:
      runs-on: ubuntu-latest
      needs: build
      # Cần quyền để deploy đến GitHub Pages
      permissions:
        pages: write
        id-token: write

      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      steps:
        - name: Download Allure report artifact
          uses: actions/download-artifact@v4
          with:
            name: allure-report
            path: allure-report

        - name: Setup Pages
          uses: actions/configure-pages@v5

        - name: Upload artifact for GitHub Pages
          uses: actions/upload-pages-artifact@v3
          with:
            path: allure-report # Đảm bảo đường dẫn này đúng với thư mục report đã tải xuống

        - name: Deploy to GitHub Pages
          id: deployment
            uses: actions/deploy-pages@v4